### ISSUE TITLE
Eliminar código de branches de no código

### ISSUE THREAD

**Issue by EmmanuelAB** [labexp/osmtracker-android_old#120]
Por ejemplo los branches `layouts` y `docu` existen sólo para tener archivos que no son del proyecto de android studio. Pienso que sería más limpio que contengan sólo lo que deberían. Yo puedo hacerlo si están de acuerdo

**Comment by jamescr** [comment]
Creo que podríamos hablar más sobre esto. En principio opino que lo que está en `docu` debería moverse a otro lugar más adecuado (wiki o sitio web) y la rama `layouts` quizás debamos moverla a otro repo solo para ese fin y con gente adicional que nos ayude a mantenerla.

**Comment by xsaco07** [comment]
Ya se pasó la info(screenshots) que estaban en `docu` a una nueva página en la Wiki y esta está respaldada en local.

**Comment by jamescr** [comment]
También se creo el repo `https://github.com/labexp/osmtracker-android-layouts` para alojar los layouts ahí. En cuanto definamos la estructura que tendrá ese repo podemos moverlas para allá.
