### ISSUE TITLE
Rename packages

### ISSUE THREAD

**Issue by jamescr** [labexp/osmtracker-android_old#121]
Looking forward to the repository transfer, a change in the Java packages have to be done. Now the packages are under Nicolas name (e.g. "me.guillaumin.android"...),  let's renamed these to something more generic before the transfer like "org.osmtracker.android". 

When ready, please make a PR directly to upstream repo.

**Comment by EmmanuelAB** [comment]
Before making the changes should I fork from `labexp/develop` or `labexp/master` ?

**Comment by jamescr** [comment]
It's not a fork but a branch from master.

**Comment by jamescr** [comment]
[This branch](https://github.com/jamescr/osmtracker-android/tree/package_rename) closes the issue. Before making the PR I would like to test it more, in case anyone could help.

**Comment by EmmanuelAB** [comment]
I have a working branch named `rename` on my repository with the domain changed from `me.guillaumin.android.osmtracker` to `org.osmtracker`. Also I've been using it and got no problems with the new name but I'd like to ask @aton1698  and @altaros97 to test also just for making sure that everyting is going OK after the renaming.

**Comment by xsaco07** [comment]
I've been testing the "Upload a trace to OSM" functionality and is not working in this moment. I get this error: "No se pudo autenticar en OSM: oauth.signpost.exception.OAuthExpectationFailedException: Authorized request token or token secret not set. Did you retrieve an authorized request token before?"

**Comment by altaros97** [comment]
We have used the changes in the branch and everything is ok.

**Comment by xsaco07** [comment]
Ok, probably I checked the functionality with the wrong version.

**Comment by EmmanuelAB** [comment]
I've made the PR.
