### ISSUE TITLE
error si el servidor de layouts prederminado no existe

### ISSUE THREAD

**Issue by jamescr** [labexp/osmtracker-android_old#124]
Cuando el servidor de layouts predeterminado no existe se cae la app. No hay oportunidad de cambiar el url del servidor ni nada. Es un error severo. 

Al solucionarlo debemos generar un apk nuevo para pruebas.

Este error es evidente ahora que el repo fue renombrado

**Comment by altaros97** [comment]
Descargué el apk del link que se encuentra en [Beta Testing](https://github.com/labexp/osmtracker-android_old/wiki/Pruebas-Beta) y no tuve ningún error. Sería conveniente que @aton1698 @EmmanuelAB y @xsaco07 probaran el apk en sus teléfonos y ver si les da el mismo error.

**Comment by xsaco07** [comment]
Hice el mismo proceso que @altaros97 con la misma apk y no tuve problema con el servidor predeterminado ni a la hora de editar el nombre del repositorio con la terminación _old. Habrá que ver qué dicen @aton1698 y @EmmanuelAB .

**Comment by aton1698** [comment]
El error creo que no tiene que ver tanto con la existencia del repo, sino con el problema que habíamos visto hace algún tiempo.Habíamos dicho que una posibilidad de ese error, era que se "caía" github.
También realicé pruebas y no tuve problemas, y cambié los parámetros del servidor y la aplicación pone un msj de servidor invalido en caso de que no encuentre el repo.

**Comment by jamescr** [comment]
Voy a intentar depurar la aplicación desde mi teléfono a ver si puedo extraer el log.
